// NEW PAPER 1 SET: History Section (1-25) - Unique fresh questions based on Bihar & UP PYQs

const paper1NewSetHistory = [
  {id: 1, question: "Who was the ancient kingdom Magadha ruled by during the 6th century BCE?", questionHindi: "प्राचीन राज्य मगध का शासन किसने किया था छठी शताब्दी ईसा पूर्व में?", options: ["Ajatashatru / अजातशत्रु", "Bimbisara / बिंबिसार", "Chandragupta Maurya / चंद्रगुप्त मौर्य", "Ashoka / अशोक"], correct: 1, subject: "History"},
  {id: 2, question: "Which ancient university was established in Bihar during the Gupta period?", questionHindi: "गुप्त काल के दौरान बिहार में कौन सा प्राचीन विश्वविद्यालय स्थापित हुआ था?", options: ["Nalanda / नालंदा", "Takshashila / तक्षशिला", "Vikramshila / विक्रमशिला", "Odantapuri / ओदंतपुरी"], correct: 0, subject: "History"},
  {id: 3, question: "Which Mughal emperor abolished the Jizya tax?", questionHindi: "किस मुग़ल सम्राट ने जिज़िया कर समाप्त किया था?", options: ["Akbar / अकबर", "Aurangzeb / औरंगजेब", "Babur / बाबर", "Jahangir / जहांगीर"], correct: 0, subject: "History"},
  {id: 4, question: "Who organized the Non-Cooperation Movement in Bihar in 1920?", questionHindi: "1920 में बिहार में असहयोग आंदोलन किसने संगठित किया था?", options: ["Rajendra Prasad / राजेंद्र प्रसाद", "Sri Krishna Sinha / श्री कृष्णा सिन्हा", "Anugrah Narayan Sinha / अनुग्रह नारायण सिन्हा", "Maghfoor Ahmad Ajazi / मगफूर अहमद अज़ाज़ी"], correct: 2, subject: "History"},
  {id: 5, question: "The Champaran Satyagraha was led by whom?", questionHindi: "चंपारण सत्याग्रह का नेतृत्व किसने किया?", options: ["Mahatma Gandhi / महात्मा गांधी", "Rajendra Prasad / राजेंद्र प्रसाद", "Bihar Kesari / बिहार केसरी", "Subhash Chandra Bose / सुभाष चंद्र बोस"], correct: 0, subject: "History"},
  {id: 6, question: "Which fort was the headquarters of Sher Shah Suri?", questionHindi: "शेर शाह सूरी का मुख्यालय कौन सा किला था?", options: ["Rohtasgarh / रोहतासगढ़", "Lahore Fort / लाहौर किला", "Firozabad Fort / फिरोजाबाद किला", "Agra Fort / आगरा किला"], correct: 0, subject: "History"},
  {id: 7, question: "Who was the Governor-General of Bengal during the First War of Independence 1857?", questionHindi: "1857 की प्रथम स्वतंत्रता संग्राम के दौरान बंगाल के गवर्नर-जनरल कौन थे?", options: ["Lord Dalhousie / लॉर्ड डलहौजी", "Lord Canning / लॉर्ड कैनिंग", "Lord Curzon / लॉर्ड कर्जन", "Lord Hastings / लॉर्ड हेस्टिंग्स"], correct: 1, subject: "History"},
  {id: 8, question: "What was the main reason for the failure of the Revolt of 1857 in Bihar?", questionHindi: "1857 के बिहार विद्रोह के विफल होने का मुख्य कारण क्या था?", options: ["Lack of unity / एकता की कमी", "British Military Strength / ब्रिटिश सैन्य शक्ति", "Failure of leadership / नेतृत्व की विफलता", "Lack of resources / संसाधनों की कमी"], correct: 0, subject: "History"},
  {id: 9, question: "Which national leader from Bihar was the first President of independent India?", questionHindi: "स्वतंत्र भारत के पहले राष्ट्रपति बिहार के कौन से नेताओं में से थे?", options: ["Rajendra Prasad / राजेंद्र प्रसाद", "Jawaharlal Nehru / जवाहरलाल नेहरू", "Sardar Patel / सरदार पटेल", "Bimal Prasad / बिमल प्रसाद"], correct: 0, subject: "History"},
  {id: 10, question: "The Champaran Satyagraha was based on protest against?", questionHindi: "चंपारण सत्याग्रह किसके विरुद्ध आंदोलन था?", options: ["Indigo plantation / नील की खेती", "Salt Tax / नमक कर", "Land Revenue / भूमि कर", "Railway tax / रेलवे कर"], correct: 0, subject: "History"},
  {id: 11, question: "The National School in Bihar was founded by whom?", questionHindi: "बिहार में राष्ट्रीय स्कूल की स्थापना किसने की थी?", options: ["Mahavir Singh / महावीर सिंह", "Sri Krishna Sinha / श्री कृष्णा सिन्हा", "Maghfoor Ahmad Ajazi / मगफूर अहमद अज़ाज़ी", "Rajendra Prasad / राजेंद्र प्रसाद"], correct: 2, subject: "History"},
  {id: 12, question: "Which major river flows through Bihar and is considered holy?", questionHindi: "बिहार से कौन सी प्रमुख नदी बहती है, जिसे पवित्र माना जाता है?", options: ["Ganga / गंगा", "Yamuna / यमुना", "Sone / सोन", "Kosi / कोसी"], correct: 0, subject: "History"},
  {id: 13, question: "Who was the first Chief Minister of Bihar after independence?", questionHindi: "स्वतंत्रता के बाद बिहार के पहले मुख्यमंत्री कौन थे?", options: ["Sri Krishna Sinha / श्री कृष्णा सिन्हा", "Anugrah Narayan Sinha / अनुग्रह नारायण सिन्हा", "Jagjivan Ram / जगजीवन राम", "Ram Manohar Lohia / राम मनोहर लोहिया"], correct: 0, subject: "History"},
  {id: 14, question: "Which treaty ended the Anglo-Sikh Wars and affected Bihar's political scenario?", questionHindi: "अंग्रेज़ों और सिखों के युद्ध को समाप्त करने वाला कौन सा संधि था जिसने बिहार के राजनीतिक परिदृश्य को प्रभावित किया?", options: ["Treaty of Amritsar / अमृतसर की संधि", "Treaty of Lahore / लाहौर की संधि", "Treaty of Allahabad / इलाहाबाद की संधि", "Treaty of Kanpur / कानपुर की संधि"], correct: 1, subject: "History"},
  {id: 15, question: "Which freedom fighter from Bihar was also a prominent socialist leader?", questionHindi: "बिहार के कौन से स्वतंत्रता सेनानी एक प्रमुख समाजवादी नेता भी थे?", options: ["Ram Manohar Lohia / राम मनोहर लोहिया", "Jayaprakash Narayan / जयप्रकाश नारायण", "Anugrah Narayan Sinha / अनुग्रह नारायण सिन्हा", "Rajendra Prasad / राजेंद्र प्रसाद"], correct: 0, subject: "History"},
  {id: 16, question: "Who played a major role in founding the All India Forward Bloc?", questionHindi: "अखिल भारतीय फॉरवर्ड ब्लॉक की स्थापना में किसका प्रमुख योगदान था?", options: ["Subhas Chandra Bose / सुभाष चंद्र बोस", "Jawaharlal Nehru / जवाहरलाल नेहरू", "Bhagat Singh / भगत सिंह", "Bal Gangadhar Tilak / बाल गंगाधर तिलक"], correct: 0, subject: "History"},
  {id: 17, question: "Which social reformer from Bihar began the movement to eradicate untouchability?", questionHindi: "बिहार के कौन से सामाजिक सुधारक ने छुआछूत खत्म करने का आंदोलन शुरू किया?", options: ["Jai Prakash Narayan", "Ramya Basu", "Rajendra Prasad", "Jaglal Choudhary"], correct: 3, subject: "History"},
  {id: 18, question: "The first session of the Indian National Congress in Bihar was held at:", questionHindi: "भारतीय राष्ट्रीय कांग्रेस का पहला सत्र बिहार में कहां हुआ था?", options: ["Patna", "Muzaffarpur", "Darbhanga", "Gaya"], correct: 1, subject: "History"},
  {id: 19, question: "Which festival in Bihar marks the beginning of the harvest season?", questionHindi: "बिहार में कौन सा त्योहार फसल के मौसम की शुरुआत को चिह्नित करता है?", options: ["Chhath Puja", "Diwali", "Holi", "Makar Sankranti"], correct: 0, subject: "History"},
  {id: 20, question: "Which year did Bihar become a separate province during British rule?", questionHindi: "ब्रिटिश शासन के दौरान बिहार कब एक अलग प्रांत बना?", options: ["1912", "1902", "1920", "1935"], correct: 0, subject: "History"},
  {id: 21, question: "Who was known as the 'Iron Man of India' and hailed from Bihar?", questionHindi: "किसे 'भारत का लोकोत्तर पुरुष' कहा जाता है जो बिहार के थे?", options: ["Sardar Vallabhbhai Patel", "Rajendra Prasad", "Jayaprakash Narayan", "Ram Manohar Lohia"], correct: 0, subject: "History"},
  {id: 22, question: "Which movement in Bihar was centered around farmers' rights during the colonial period?", questionHindi: "औपनिवेशिक काल में बिहार में किस आंदोलन का केंद्र किसानों के अधिकार थे?", options: ["Tebhaga Movement", "Champaran Movement", "Bijli Andolan", "Kisan Sabha Movement"], correct: 3, subject: "History"},
  {id: 23, question: "Which document served as the basis for the Indian Constitution?", questionHindi: "भारतीय संविधान का आधार कौन सा दस्तावेज था?", options: ["Government of India Act 1935", "Indian Councils Act 1909", "Montagu-Chelmsford Reforms", "Simon Commission Report"], correct: 0, subject: "History"},
  {id: 24, question: "Which treaty between British government and Indian rulers weakened princely states?", questionHindi: "ब्रिटिश सरकार और भारतीय शासकों के बीच कौन सा संधि रियासतों को कमजोर किया?", options: ["Doctrine of Lapse", "Rowlatt Act", "Delhi Pact", "Treaty of Allahabad"], correct: 0, subject: "History"},
  {id: 25, question: "Which tribal leader from Bihar led a rebellion against British in 1857?", questionHindi: "किस बिहार के आदिवासी नेता ने 1857 में ब्रिटिशों के खिलाफ विद्रोह किया?", options: ["Tekam Turi", "Thakur Ram Prasad", "Kunwar Singh", "Sukhdeo"], correct: 2, subject: "History"},
];

// PAPER 1 NEW SET: Geography Section (26-55)

const paper1NewSetGeography = [
  {id: 26, question: "Which river is the longest in India?", questionHindi: "भारत की सबसे लंबी नदी कौन सी है?", options: ["Ganga / गंगा", "Yamuna / यमुना", "Godavari / गोदावरी", "Brahmaputra / ब्रह्मपुत्र"], correct: 0, subject: "Geography"},
  {id: 27, question: "The Deccan Plateau is composed mainly of which rock type?", questionHindi: "डेक्कन पठार मुख्य रूप से किस प्रकार के चट्टान से बना है?", options: ["Basalt / बेसाल्ट", "Granite / ग्रेनाइट", "Sandstone / बलुआ पत्थर", "Limestone / चूना पत्थर"], correct: 0, subject: "Geography"},
  {id: 28, question: "Which State in India has the highest population density?", questionHindi: "भारत का कौन सा राज्य सबसे अधिक जनसंख्या घनत्व वाला है?", options: ["Bihar / बिहार", "Uttar Pradesh / उत्तर प्रदेश", "West Bengal / पश्चिम बंगाल", "Delhi / दिल्ली"], correct: 3, subject: "Geography"},
  {id: 29, question: "The Eastern Ghats run parallel to which coast?", questionHindi: "पूर्वी घाट भारत के किस तट के समानांतर चलते हैं?", options: ["Western Coast / पश्चिमी तट", "Eastern Coast / पूर्वी तट", "Northern Coast / उत्तरी तट", "Southern Coast / दक्षिणी तट"], correct: 1, subject: "Geography"},
  {id: 30, question: "Which mineral is mainly mined in Bihar?", questionHindi: "बिहार में मुख्य रूप से कौन सा खनिज निकाला जाता है?", options: ["Coal / कोयला", "Iron ore / लौह अयस्क", "Bauxite / बॉक्साइट", "Mica / अभ्रक"], correct: 3, subject: "Geography"},
  {id: 31, question: "Which river is called the 'Dakshin Ganga'?", questionHindi: "कौन सी नदी को 'दक्षिण गंगा' कहा जाता है?", options: ["Godavari / गोदावरी", "Krishna / कृष्णा", "Cauvery / कावेरी", "Narmada / नर्मदा"], correct: 0, subject: "Geography"},
  {id: 32, question: "Which of these is an example of a non-renewable resource?", questionHindi: "निम्नलिखित में से कौन सा गैर नवीकरणीय संसाधन है?", options: ["Solar Energy / सूर्य ऊर्जा", "Wind Energy / पवन ऊर्जा", "Coal / कोयला", "Hydroelectric Power / जल विद्युत शक्ति"], correct: 2, subject: "Geography"},
  {id: 33, question: "Which soil is found mostly in the Indo-Gangetic plain?", questionHindi: "इंडो-गंगा मैदान में मुख्यत: कौन सी मिट्टी पाई जाती है?", options: ["Alluvial Soil / जलोढ़ मिट्टी", "Black Soil / काली मिट्टी", "Red Soil / लाल मिट्टी", "Laterite Soil / लेटराइट मिट्टी"], correct: 0, subject: "Geography"},
  {id: 34, question: "Which state has the largest coal reserves in India?", questionHindi: "भारत में किस राज्य के पास सबसे अधिक कोयला भंडार है?", options: ["Jharkhand / झारखंड", "Odisha / ओडिशा", "Chhattisgarh / छत्तीसगढ़", "West Bengal / पश्चिम बंगाल"], correct: 0, subject: "Geography"},
  {id: 35, question: "Which city is known as the 'Manchester of India'?", questionHindi: "भारत के किस शहर को 'मैनचेस्टर ऑफ इंडिया' कहा जाता है?", options: ["Mumbai / मुंबई", "Ahmedabad / अहमदाबाद", "Kolkata / कोलकाता", "Chennai / चेन्नई"], correct: 1, subject: "Geography"},
  {id: 36, question: "Which one among these is a fossil fuel?", questionHindi: "निम्नलिखित में से कौन सा जीवाश्म ईंधन है?", options: ["Petrol / पेट्रोल", "Natural Gas / प्राकृतिक गैस", "Solar Energy / सौर ऊर्जा", "Electricity / बिजली"], correct: 1, subject: "Geography"},
  {id: 37, question: "Which river forms the boundary between India and Bangladesh?", questionHindi: "कौन सी नदी भारत और बांग्लादेश के बीच सीमा बनाती है?", options: ["Ganga / गंगा", "Meghna / मेघना", "Padma / पद्मा", "Brahmaputra / ब्रह्मपुत्र"], correct: 2, subject: "Geography"},
  {id: 38, question: "Which mountain range is older, the Himalayas or Aravallis?", questionHindi: "कौन सी पर्वत श्रृंखला पुरानी है, हिमालय या अरावली?", options: ["Himalayas / हिमालय", "Aravallis / अरावली"], correct: 1, subject: "Geography"},
  {id: 39, question: "Which state in India receives the highest rainfall?", questionHindi: "भारत में कौन सा राज्य सबसे अधिक वर्षा प्राप्त करता है?", options: ["Meghalaya / मेघालय", "Assam / असम", "Kerala / केरल", "West Bengal / पश्चिम बंगाल"], correct: 0, subject: "Geography"},
  {id: 40, question: "Which one of the following is a major port on the west coast of India?", questionHindi: "निम्नलिखित में से कौन सा भारत के पश्चिमी तट पर स्थित एक प्रमुख बंदरगाह है?", options: ["Kolkata / कोलकाता", "Mumbai / मुंबई", "Chennai / चेन्नई", "Paradip / पारादीप"], correct: 1, subject: "Geography"},
  {id: 41, question: "The phenomenon of 'El Niño' affects which part of India?", questionHindi: "'एल नीनो' प्रभाव भारत के किस हिस्से को प्रभावित करता है?", options: ["North-East India / उत्तर-पूर्व भारत", "South India / दक्षिण भारत", "Western India / पश्चिम भारत", "Eastern India / पूर्वी भारत"], correct: 2, subject: "Geography"},
  {id: 42, question: "Which crop is called the 'Golden Fibre'?", questionHindi: "किस फसल को 'गोल्डन फाइबर' कहा जाता है?", options: ["Cotton / कपास", "Jute / जूट", "Silk / रेशम", "Wool / ऊन"], correct: 1, subject: "Geography"},
  {id: 43, question: "Which of the following states is known for tea production?", questionHindi: "निम्नलिखित राज्यों में से कौन चाय उत्पादन के लिए प्रसिद्ध है?", options: ["Assam / असम", "Rajasthan / राजस्थान", "Punjab / पंजाब", "Haryana / हरियाणा"], correct: 0, subject: "Geography"},
  {id: 44, question: "Which among the following is NOT a tribal state in India?", questionHindi: "निम्नलिखित में से कौन सा भारत में एक आदिवासी राज्य नहीं है?", options: ["Jharkhand / झारखंड", "Rajasthan / राजस्थान", "Chhattisgarh / छत्तीसगढ़", "Madhya Pradesh / मध्य प्रदेश"], correct: 1, subject: "Geography"},
  {id: 45, question: "Which soil is suitable for the cultivation of rice?", questionHindi: "किस मिट्टी में धान की खेती ठीक होती है?", options: ["Alluvial Soil / जलोढ़ मिट्टी", "Black Soil / काली मिट्टी", "Red Soil / लाल मिट्टी", "Desert Soil / रेगिस्तानी मिट्टी"], correct: 0, subject: "Geography"},
  {id: 46, question: "Which river basin covers the largest area in India?", questionHindi: "भारत में कौन सा नदी बेसिन सबसे बड़ा क्षेत्र घेरता है?", options: ["Ganga Basin / गंगा बेसिन", "Godavari Basin / गोदावरी बेसिन", "Indus Basin / सिंधु बेसिन", "Brahmaputra Basin / ब्रह्मपुत्र बेसिन"], correct: 0, subject: "Geography"},
  {id: 47, question: "Which is the largest freshwater lake in India?", questionHindi: "भारत की सबसे बड़ी ताजा पानी की झील कौन सी है?", options: ["Wular Lake / वुलर झील", "Chilika Lake / चिलिका झील", "Dal Lake / डल झील", "Loktak Lake / लोकटक झील"], correct: 0, subject: "Geography"},
  {id: 48, question: "The city of Bhubaneswar is in which state?", questionHindi: "भुवनेश्वर शहर किस राज्य में है?", options: ["Odisha / ओडिशा", "Jharkhand / झारखंड", "Bihar / बिहार", "West Bengal / पश्चिम बंगाल"], correct: 0, subject: "Geography"},
  {id: 49, question: "India's largest coal-producing state is:", questionHindi: "भारत का सबसे बड़ा कोयला उत्पादक राज्य है:", options: ["Jharkhand / झारखंड", "Chhattisgarh / छत्तीसगढ़", "Odisha / ओडिशा", "West Bengal / पश्चिम बंगाल"], correct: 0, subject: "Geography"},
  {id: 50, question: "Which place is famous for the 'Festival of Lights' known as Diwali?", questionHindi: "दिवाली के नाम से प्रसिद्ध 'दीयों का त्योहार' किस स्थान पर मनाया जाता है?", options: ["Varanasi / वाराणसी", "Mathura / मथुरा", "Jaipur / जयपुर", "Mumbai / मुंबई"], correct: 0, subject: "Geography"},
  {id: 51, question: "The eastern boundary of India shares a border with:", questionHindi: "भारत की पूर्वी सीमा किस देश से लगती है?", options: ["Pakistan / पाकिस्तान", "China / चीन", "Bangladesh / बांग्लादेश", "Nepal / नेपाल"], correct: 2, subject: "Geography"},
  {id: 52, question: "Which sector employs the largest percentage of India's workforce?", questionHindi: "भारत की कार्यबल का सबसे बड़ा प्रतिशत किस क्षेत्र में रोजगार करता है?", options: ["Agriculture / कृषि", "Industry / उद्योग", "Services / सेवा", "Trade / व्यापार"], correct: 0, subject: "Geography"},
  {id: 53, question: "Which is the predominant climate in Rajasthan?", questionHindi: "राजस्थान में प्रमुख जलवायु प्रकार कौन सा है?", options: ["Desert / रेगिस्तानी", "Tropical / उष्णकटिबंधीय", "Temperate / समशीतोष्ण", "Alpine / अल्पाइन"], correct: 0, subject: "Geography"},
  {id: 54, question: "Which state is the largest producer of tea in India?", questionHindi: "भारत में सबसे अधिक चाय उत्पादन किस राज्य में होता है?", options: ["Assam / असम", "West Bengal / पश्चिम बंगाल", "Tamil Nadu / तमिलनाडु", "Kerala / केरल"], correct: 0, subject: "Geography"},
  {id: 55, question: "Which is the red soil region of India predominant in?", questionHindi: "भारत के लाल मिट्टी क्षेत्र मुख्य रूप से किसके लिए उपयुक्त हैं?", options: ["Rabi crops / रबी फसलें", "Kharif crops / खरीफ फसलें", "Vegetables / सब्जियां", "Plantation crops / बागवानी"], correct: 1, subject: "Geography"},
];

// PAPER 1 NEW SET: Civics, Economics, Pedagogy (56-100)

const paper1NewSetRemaining = [
  // Civics (Q56-70)
  {id: 56, question: "Who has the right to dissolve the Lok Sabha?", questionHindi: "लोकसभा को भंग करने का अधिकार किसके पास है?", options: ["President / राष्ट्रपति", "Prime Minister / प्रधानमंत्री", "Parliament / संसद", "Supreme Court / सर्वोच्च न्यायालय"], correct: 0, subject: "Civics"},
  {id: 57, question: "Which article of the Constitution provides fundamental duties?", questionHindi: "संविधान का कौन सा अनुच्छेद मौलिक कर्तव्य प्रदान करता है?", options: ["Article 51A", "Article 32", "Article 15", "Article 19"], correct: 0, subject: "Civics"},
  {id: 58, question: "How many members can the president nominate to Rajya Sabha?", questionHindi: "राष्ट्रपति राज्यसभा में कितने सदस्यों को नामित कर सकते हैं?", options: ["10", "12", "14", "15"], correct: 1, subject: "Civics"},
  {id: 59, question: "Money bill can be introduced only in:", questionHindi: "धन विधेयक केवल किसमें पेश किया जा सकता है?", options: ["Lok Sabha / लोकसभा", "Rajya Sabha / राज्यसभा", "Both houses / दोनों सदनों में", "Either house / किसी भी सदन में"], correct: 0, subject: "Civics"},
  {id: 60, question: "The Speaker of Lok Sabha is elected by:", questionHindi: "लोकसभा का अध्यक्ष किसके द्वारा चुना जाता है?", options: ["President / राष्ट्रपति", "Members of Lok Sabha / लोकसभा सदस्य", "Prime Minister / प्रधानमंत्री", "Members of Rajya Sabha / राज्यसभा सदस्य"], correct: 1, subject: "Civics"},
  {id: 61, question: "Directive Principles in the Constitution guide:", questionHindi: "संविधान में राज्य की नीति के निर्देशात्मक सिद्धांत किसका मार्गदर्शन करते हैं?", options: ["Legislature / विधानसभा", "Executive / कार्यपालिका", "Judiciary / न्यायपालिका", "All of the above / उपर्युक्त सभी"], correct: 3, subject: "Civics"},
  {id: 62, question: "Which body administers the election of the President of India?", questionHindi: "भारत के राष्ट्रपति के चुनाव को कौन संचालित करता है?", options: ["Election Commission / निर्वाचन आयोग", "Supreme Court / सर्वोच्च न्यायालय", "Parliament / संसद", "Prime Minister / प्रधानमंत्री"], correct: 0, subject: "Civics"},
  {id: 63, question: "The following is NOT a fundamental right:", questionHindi: "निम्नलिखित में से कौन सा मूल अधिकार नहीं है?", options: ["Right to education / शिक्षा का अधिकार", "Right to property / संपत्ति का अधिकार", "Right to freedom of speech / अभिव्यक्ति की स्वतंत्रता का अधिकार", "Right to constitutional remedies / संवैधानिक उपचारों का अधिकार"], correct: 1, subject: "Civics"},
  {id: 64, question: "Who is known as the 'Father of the Indian Constitution'?", questionHindi: "'भारतीय संविधान के जनक' के रूप में किसे जाना जाता है?", options: ["Dr. B.R. Ambedkar / डॉ. भीमराव अम्बेडकर", "Jawaharlal Nehru / जवाहरलाल नेहरू", "Sardar Patel / सरदार पटेल", "Rajendra Prasad / राजेंद्र प्रसाद"], correct: 0, subject: "Civics"},
  {id: 65, question: "The Constitutional Assembly was formed in:", questionHindi: "संविधान सभा की स्थापना कब हुई थी?", options: ["1946", "1945", "1947", "1942"], correct: 0, subject: "Civics"},
  {id: 66, question: "The fundamental duties were added by the:", questionHindi: "मौलिक कर्तव्य किस संशोधन से जोड़े गए?", options: ["42nd Amendment / 42वां संशोधन", "44th Amendment / 44वां संशोधन", "61st Amendment / 61वां संशोधन", "73rd Amendment / 73वां संशोधन"], correct: 0, subject: "Civics"},
  {id: 67, question: "How many schedules does the Indian Constitution have?", questionHindi: "भारतीय संविधान में कितनी अनुसूचियां हैं?", options: ["8", "10", "12", "14"], correct: 3, subject: "Civics"},
  {id: 68, question: "Who appoints the Chief Election Commissioner of India?", questionHindi: "भारत के मुख्य निर्वाचन आयुक्त की नियुक्ति कौन करता है?", options: ["President / राष्ट्रपति", "Prime Minister / प्रधानमंत्री", "Parliament / संसद", "Supreme Court / सर्वोच्च न्यायालय"], correct: 0, subject: "Civics"},
  {id: 69, question: "Which Article provides for the Right to Equality?", questionHindi: "कौन सा अनुच्छेद समानता के अधिकार के लिए है?", options: ["Article 14", "Article 15", "Article 16", "Article 17"], correct: 0, subject: "Civics"},
  {id: 70, question: "Rajya Sabha is the:", questionHindi: "राज्यसभा है:", options: ["Lower house / निचला सदन", "Upper house / उच्च सदन", "Legislative body / विधानप्रिय निकाय", "Executive body / कार्यकारी निकाय"], correct: 1, subject: "Civics"},

  // Economics (Q71-85)
  {id: 71, question: "GDP of a country is calculated by which sector's contribution?", questionHindi: "किस क्षेत्र के योगदान से किसी देश का GDP मापा जाता है?", options: ["Agriculture / कृषि", "Industry / उद्योग", "Services / सेवा", "All sectors combined / सभी क्षेत्र संयुक्त"], correct: 3, subject: "Economics"},
  {id: 72, question: "Which among these is a primary sector activity?", questionHindi: "इनमें से कौन सी प्राथमिक क्षेत्र की गतिविधि है?", options: ["Fishing / मछली पकड़ना", "Manufacturing / निर्माण", "Banking / बैंकिंग", "Teaching / शिक्षण"], correct: 0, subject: "Economics"},
  {id: 73, question: "Which institution manages the currency supply in India?", questionHindi: "भारत में मुद्रा आपूर्ति का प्रबंधन कौन करता है?", options: ["RBI", "Finance Ministry / वित्त मंत्रालय", "SEBI", "Planning Commission"], correct: 0, subject: "Economics"},
  {id: 74, question: "Microfinance is primarily targeted towards:", questionHindi: "माइक्रोफाइनेंस मुख्यतः किसके लिए है?", options: ["Small borrowers / छोटे उधारकर्ता", "Large industrialists / बड़े उद्योगपति", "Government / सरकार", "Banks / बैंक"], correct: 0, subject: "Economics"},
  {id: 75, question: "What does inflation mean?", questionHindi: "मुद्रास्फीति का क्या मतलब है?", options: ["Decrease in prices / कीमतों में कमी", "Increase in general price levels / सामान्य कीमतों में वृद्धि", "Stable prices / कीमतों का स्थिर होना", "Government control / सरकारी नियंत्रण"], correct: 1, subject: "Economics"},
  {id: 76, question: "Which type of tax is GST?", questionHindi: "GST किस प्रकार का कर है?", options: ["Direct tax / प्रत्यक्ष कर", "Indirect tax / अप्रत्यक्ष कर", "Income tax / आयकर", "Property tax / संपत्ति कर"], correct: 1, subject: "Economics"},
  {id: 77, question: "The Planning Commission was replaced by:", questionHindi: "नियोजन आयोग की जगह किसने ली?", options: ["NITI Aayog", "Finance Ministry", "Economic Survey", "RBI"], correct: 0, subject: "Economics"},
  {id: 78, question: "Which body controls the stock markets in India?", questionHindi: "भारत में स्टॉक मार्केट का नियंत्रण कौन करता है?", options: ["SEBI", "RBI", "Finance Ministry", "Planning Commission"], correct: 0, subject: "Economics"},
  {id: 79, question: "What is 'Demand' in economics?", questionHindi: "अर्थशास्त्र में 'मांग' का क्या अर्थ है?", options: ["Willingness to buy / खरीदने की इच्छा", "Ability to pay / भुगतान क्षमता", "Willingness and ability to buy / खरीदने की इच्छा और क्षमता", "None of these / इनमें से कोई नहीं"], correct: 2, subject: "Economics"},
  {id: 80, question: "Which of the following is a renewable energy source?", questionHindi: "निम्नलिखित में से कौन सा अक्षय ऊर्जा स्रोत है?", options: ["Coal / कोयला", "Petrol / पेट्रोल", "Wind Energy / पवन ऊर्जा", "Natural Gas / प्राकृतिक गैस"], correct: 2, subject: "Economics"},
  {id: 81, question: "Which crop is known as the 'Queen of Cereals'?", questionHindi: "कौन सी फसल को 'अन्नों की रानी' कहा जाता है?", options: ["Rice / चावल", "Wheat / गेहूं", "Maize / मक्का", "Barley / जौ"], correct: 0, subject: "Economics"},
  {id: 82, question: "Who is the current Finance Minister of India (2025)?", questionHindi: "भारत के वर्तमान वित्त मंत्री कौन हैं (2025)?", options: ["Nirmala Sitharaman", "Arun Jaitley", "Piyush Goyal", "Raghuram Rajan"], correct: 0, subject: "Economics"},
  {id: 83, question: "Which sector contributes maximum to India's GDP?", questionHindi: "भारत की GDP में अधिकतम योगदान कौन सा क्षेत्र देता है?", options: ["Agriculture", "Industry", "Services", "Mining"], correct: 2, subject: "Economics"},
  {id: 84, question: "Which Indian city is famous for IT industry?", questionHindi: "कौन सा भारतीय शहर आईटी उद्योग के लिए प्रसिद्ध है?", options: ["Bangalore", "Chennai", "Pune", "Lucknow"], correct: 0, subject: "Economics"},
  {id: 85, question: "Which institution publishes India's Economic Survey every year?", questionHindi: "भारत की आर्थिक समीक्षा हर साल कौन प्रकाशित करता है?", options: ["Finance Ministry", "Planning Commission", "NITI Aayog", "RBI"], correct: 0, subject: "Economics"}
];
// PAPER 1 NEW SET: Pedagogy and Others (Q86-100)

const paper1NewSetPedagogyOthers = [
  {id: 86, question: "Who is known as the father of modern education?", questionHindi: "आधुनिक शिक्षा के जनक किसे कहा जाता है?", options: ["John Dewey / जॉन ड्यूवी", "Maria Montessori / मारिया मोंटेसरी", "Rabindranath Tagore / रवींद्रनाथ टैगोर", "Swami Vivekananda / स्वामी विवेकानंद"], correct: 0, subject: "Pedagogy"},
  {id: 87, question: "Which learning theory focuses on rewards and punishments?", questionHindi: "कौन सा सीखने का सिद्धांत पुरस्कार और दंड पर केंद्रित है?", options: ["Operant Conditioning / ऑपेरेंट कंडीशनिंग", "Classical Conditioning / शास्त्रीय कंडीशनिंग", "Social Learning / सामाजिक सीखना", "Cognitive Learning / संज्ञानात्मक सीखना"], correct: 0, subject: "Pedagogy"},
  {id: 88, question: "In the educational context, CCE stands for:", questionHindi: "शैक्षिक संदर्भ में, CCE का क्या अर्थ है?", options: ["Continuous and Comprehensive Evaluation / सतत और व्यापक मूल्यांकन", "Child Care Education / बाल देखभाल शिक्षा", "Creative and Critical Education / रचनात्मक और आलोचनात्मक शिक्षा", "Certified Classroom Education / प्रमाणित कक्षा शिक्षा"], correct: 0, subject: "Pedagogy"},
  {id: 89, question: "Which of the following is NOT a type of assessment used in schools?", questionHindi: "निम्नलिखित में से कौन स्कूलों में उपयोग की जाने वाली मूल्यांकन की प्रकार नहीं है?", options: ["Formative / प्रारूपिक", "Summative / संक्षेपणात्मक", "Creative / रचनात्मक", "Diagnostic / निदानात्मक"], correct: 2, subject: "Pedagogy"},
  {id: 90, question: "Which psychologist developed the theory of cognitive development?", questionHindi: "किस मनोवैज्ञानिक ने संज्ञानात्मक विकास का सिद्धांत विकसित किया?", options: ["Jean Piaget / जीन पियाजे", "B.F. Skinner / बीएफ स्किनर", "Lev Vygotsky / लेव विगोत्स्की", "Howard Gardner / हावर्ड गार्डनर"], correct: 0, subject: "Pedagogy"},
  {id: 91, question: "The zone of proximal development (ZPD) is a concept developed by:", questionHindi: "नजदीकी विकास क्षेत्र (ZPD) की अवधारणा किसने विकसित की?", options: ["Lev Vygotsky / लेव विगोत्स्की", "Jean Piaget / जीन पियाजे", "Erik Erikson / एरिक एरिकसन", "John Dewey / जॉन ड्यूवी"], correct: 0, subject: "Pedagogy"},
  {id: 92, question: "Who is credited with the Theory of Multiple Intelligences?", questionHindi: "बहु-बुद्धि के सिद्धांत का श्रेय किसे जाता है?", options: ["Howard Gardner / हावर्ड गार्डनर", "Jean Piaget / जीन पियाजे", "Sigmund Freud / सिगमंड फ्रायड", "Carl Jung / कार्ल जंग"], correct: 0, subject: "Pedagogy"},
  {id: 93, question: "Which method of teaching emphasizes learning by doing?", questionHindi: "कौन सी शिक्षण पद्धति 'करके सीखना' पर जोर देती है?", options: ["Project Method / परियोजना विधि", "Lecture Method / व्याख्यान विधि", "Discussion Method / चर्चा विधि", "Demonstration Method / प्रदर्शन विधि"], correct: 0, subject: "Pedagogy"},
  {id: 94, question: "What is scaffolding in education?", questionHindi: "शिक्षा में 'स्कैफोल्डिंग' का क्या अर्थ है?", options: ["Supporting learners to achieve goals / लक्ष्यों को प्राप्त करने में सहायता करना", "Teaching only advanced students / केवल उन्नत छात्रों को शिक्षित करना", "Classroom decoration / कक्षा सजावट", "Assessing students / छात्रों का मूल्यांकन करना"], correct: 0, subject: "Pedagogy"},
  {id: 95, question: "Which of the following disabilities is characterized by difficulty in reading?", questionHindi: "निम्नलिखित में से कौन सी अक्षमता पढ़ने में कठिनाई से संबंधित है?", options: ["Dyslexia / डिस्लेक्सिया", "Dysgraphia / डिसग्राफिया", "ADHD / ध्यान अभाव", "Autism / स्व-संबधित बाधा"], correct: 0, subject: "Pedagogy"},
  {id: 96, question: "Which act made education a fundamental right for children aged 6-14 in India?", questionHindi: "भारत में 6-14 वर्ष के बच्चों के लिए शिक्षा को मौलिक अधिकार बनाने वाला अधिनियम कौन सा है?", options: ["Right to Education Act, 2009 / शिक्षा का अधिकार अधिनियम, 2009", "National Education Policy, 2020 / राष्ट्रीय शिक्षा नीति, 2020", "Sarva Shiksha Abhiyan / सर्व शिक्षा अभियान", "Mid-Day Meal Scheme / मध्याह्न भोजन योजना"], correct: 0, subject: "Pedagogy"},
  {id: 97, question: "Inclusive education refers to:", questionHindi: "समावेशी शिक्षा का क्या अर्थ है?", options: ["Educating children with special needs alongside others / विशेष ज़रूरतों वाले बच्चों को अन्य बच्चों के साथ पढ़ाना", "Separate schooling for disabled children / विकलांग बच्चों के लिए अलग स्कूलिंग", "Online education / ऑनलाइन शिक्षा", "Vocational training / व्यावसायिक प्रशिक्षण"], correct: 0, subject: "Pedagogy"},
  {id: 98, question: "Which of the following is NOT included in Bloom's taxonomy?", questionHindi: "निम्नलिखित में से कौन ब्लूम के वर्गीकरण में शामिल नहीं है?", options: ["Remembering", "Analyzing", "Creating", "Ignoring"], correct: 3, subject: "Pedagogy"},
  {id: 99, question: "Continuous and Comprehensive Evaluation (CCE) aims at:", questionHindi: "सतत और व्यापक मूल्यांकन (CCE) का उद्देश्य क्या है?", options: ["Holistic assessment of students / छात्रों का समग्र मूल्यांकन", "Annual examination only / केवल वार्षिक परीक्षा", "Teacher evaluation / शिक्षक मूल्यांकन", "None of the above / उपरोक्त में से कोई नहीं"], correct: 0, subject: "Pedagogy"},
  {id: 100, question: "What does intrinsic motivation mean?", questionHindi: "आंतरिक प्रेरणा का क्या मतलब होता है?", options: ["Motivation coming from within the individual / व्यक्ति के भीतर से उत्पन्न प्रेरणा", "Motivation based on external rewards / बाहरी पुरस्कार पर आधारित प्रेरणा", "Motivation forced by rules / नियमों द्वारा प्रेरित", "Lack of motivation / प्रेरणा की कमी"], correct: 0, subject: "Pedagogy"},
];

// PAPER 1 NEW SET: GK, Environment, Math Aptitude & Logical Reasoning (Q101-150)

const paper1NewSetOtherSubjects = [
  // General Knowledge (Q101-115)
  {id: 101, question: "Who is the current President of India (2025)?", questionHindi: "भारत के वर्तमान राष्ट्रपति कौन हैं (2025)?", options: ["Droupadi Murmu", "Ram Nath Kovind", "Pranab Mukherjee", "Venkaiah Naidu"], correct: 0, subject: "GK"},
  {id: 102, question: "World Health Day is observed on:", questionHindi: "विश्व स्वास्थ्य दिवस कब मनाया जाता है?", options: ["7 April", "1 May", "15 August", "26 January"], correct: 0, subject: "GK"},
  {id: 103, question: "India won its first Olympic gold medal in which sport?", questionHindi: "भारत ने अपना पहला ओलंपिक स्वर्ण पदक किस खेल में जीता था?", options: ["Hockey", "Wrestling", "Boxing", "Badminton"], correct: 0, subject: "GK"},
  {id: 104, question: "Which is the longest river in the world?", questionHindi: "विश्व की सबसे लंबी नदी कौन सी है?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1, subject: "GK"},
  {id: 105, question: "Which country is the largest producer of coffee?", questionHindi: "कॉफ़ी का सबसे बड़ा उत्पादक देश कौन है?", options: ["Brazil", "India", "Vietnam", "Colombia"], correct: 0, subject: "GK"},
  {id: 106, question: "Which Indian state is the largest producer of spices?", questionHindi: "भारत का सबसे बड़ा मसाला उत्पादक राज्य कौन सा है?", options: ["Kerala", "Punjab", "Gujarat", "Madhya Pradesh"], correct: 0, subject: "GK"},
  {id: 107, question: "The currency of Japan is called:", questionHindi: "जापान की मुद्रा को क्या कहा जाता है?", options: ["Yuan", "Yen", "Won", "Dollar"], correct: 1, subject: "GK"},
  {id: 108, question: "The scientist C.V. Raman is known for which discovery?", questionHindi: "वैज्ञानिक सी.वी. रमन किस खोज के लिए जाने जाते हैं?", options: ["Raman Effect", "Photoelectric Effect", "Radioactivity", "Polio vaccine"], correct: 0, subject: "GK"},
  {id: 109, question: "Which planet is closest to the sun?", questionHindi: "सूर्य के सबसे करीब ग्रह कौन सा है?", options: ["Mercury", "Venus", "Earth", "Mars"], correct: 0, subject: "GK"},
  {id: 110, question: "Which planet is known as ‘Blue Planet’?", questionHindi: "किस ग्रह को ‘नीला ग्रह’ कहा जाता है?", options: ["Earth", "Uranus", "Neptune", "Jupiter"], correct: 0, subject: "GK"},
  {id: 111, question: "Which Indian festival is known as the ‘Festival of Lights’?", questionHindi: "भारत का कौन सा त्योहार ‘दीयों का त्योहार’ के नाम से जाना जाता है?", options: ["Diwali", "Holi", "Navratri", "Eid"], correct: 0, subject: "GK"},
  {id: 112, question: "The Indian Space Research Organisation (ISRO) is headquartered in:", questionHindi: "भारतीय अंतरिक्ष अनुसंधान संगठन (इसरो) का मुख्यालय कहां है?", options: ["Bangalore", "Mumbai", "Delhi", "Chennai"], correct: 0, subject: "GK"},
  {id: 113, question: "Which country invented paper?", questionHindi: "कागज का आविष्कार किस देश में हुआ?", options: ["China", "India", "Egypt", "Greece"], correct: 0, subject: "GK"},
  {id: 114, question: "Which animal is known as the ‘Ship of the Desert’?", questionHindi: "कौन सा जानवर ‘रेगिस्तान का जहाज’ कहा जाता है?", options: ["Camel", "Horse", "Donkey", "Elephant"], correct: 0, subject: "GK"},
  {id: 115, question: "The national bird of India is:", questionHindi: "भारत का राष्ट्रीय पक्षी कौन सा है?", options: ["Peacock", "Sparrow", "Eagle", "Parrot"], correct: 0, subject: "GK"},
  
  // Environment (Q116-130)
  {id: 116, question: "The main cause of global warming is:", questionHindi: "वैश्विक ताप में वृद्धि का मुख्य कारण है:", options: ["Greenhouse gases", "Deforestation", "Water pollution", "Soil erosion"], correct: 0, subject: "Environment"},
  {id: 117, question: "The Kyoto Protocol is related to:", questionHindi: "क्योटो प्रोटोकॉल किससे सम्बन्धित है?", options: ["Climate change", "International trade", "Nuclear disarmament", "Human rights"], correct: 0, subject: "Environment"},
  {id: 118, question: "Ozone Layer protects us from:", questionHindi: "ओजोन परत हमें किससे बचाती है?", options: ["Ultraviolet rays", "Infrared rays", "X-rays", "Gamma rays"], correct: 0, subject: "Environment"},
  {id: 119, question: "Which gas causes acid rain?", questionHindi: "कौन सी गैस अम्लीय वर्षा का कारण बनती है?", options: ["Sulfur dioxide", "Nitrogen", "Oxygen", "Carbon dioxide"], correct: 0, subject: "Environment"},
  {id: 120, question: "Deforestation leads to:", questionHindi: "वनों की कटाई का क्या परिणाम होता है?", options: ["Soil erosion", "Air pollution", "Water conservation", "Flood control"], correct: 0, subject: "Environment"},
  {id: 121, question: "Which is the largest producer of solar energy in India?", questionHindi: "भारत में सौर ऊर्जा का सबसे बड़ा उत्पादक कौन है?", options: ["Rajasthan", "Gujarat", "Tamil Nadu", "Maharashtra"], correct: 0, subject: "Environment"},
  {id: 122, question: "Biodegradable waste is:", questionHindi: "जैव विघटनशील कचरा क्या है?", options: ["Can decompose naturally", "Cannot decompose", "Plastic waste", "Metal waste"], correct: 0, subject: "Environment"},
  {id: 123, question: "Which of the following is a renewable energy source?", questionHindi: "निम्नलिखित में से अक्षय ऊर्जा स्रोत कौन सा है?", options: ["Coal", "Natural gas", "Solar energy", "Petroleum"], correct: 2, subject: "Environment"},
  {id: 124, question: "The greenhouse effect increases due to the rise in:", questionHindi: "ग्रीनहाउस प्रभाव किस कारण बढ़ता है?", options: ["Carbon dioxide", "Ozone layer", "Nitrogen", "Oxygen"], correct: 0, subject: "Environment"},
  {id: 125, question: "The Clean India Mission is also known as:", questionHindi: "स्वच्छ भारत मिशन को अन्य क्या कहा जाता है?", options: ["Swachh Bharat Abhiyan", "Jal Shakti Abhiyan", "Digital India", "Make in India"], correct: 0, subject: "Environment"},
  {id: 126, question: "Which of the following is a non-renewable energy source?", questionHindi: "निम्नलिखित में से कौन सा गैर-नवीकरणीय ऊर्जा स्रोत है?", options: ["Wind Energy", "Coal", "Solar Energy", "Hydro Energy"], correct: 1, subject: "Environment"},
  {id: 127, question: "Which of the following is a cause of air pollution?", questionHindi: "वायु污染 का कारण कौन सा है?", options: ["Burning of fossil fuels", "Planting trees", "Rainfall", "Use of solar energy"], correct: 0, subject: "Environment"},
  {id: 128, question: "Which one of the following is a greenhouse gas?", questionHindi: "निम्नलिखित में से कौन सी गैस ग्रीनहाउस गैस है?", options: ["Methane", "Oxygen", "Nitrogen", "Helium"], correct: 0, subject: "Environment"},
  {id: 129, question: "Earth Day is observed on:", questionHindi: "पृथ्वी दिवस कब मनाया जाता है?", options: ["22 April", "5 June", "1 May", "15 August"], correct: 0, subject: "Environment"},
  {id: 130, question: "The main constituent of natural gas is:", questionHindi: "प्राकृतिक गैस का मुख्य घटक क्या है?", options: ["Methane", "Carbon Dioxide", "Oxygen", "Nitrogen"], correct: 0, subject: "Environment"},
  
  // Math Aptitude & Logical Reasoning (Q131-150)
  {id: 131, question: "What is the square root of 144?", questionHindi: "144 का वर्गमूल क्या है?", options: ["10", "11", "12", "13"], correct: 2, subject: "Math"},
  {id: 132, question: "If the price of an item is increased by 25%, the new price is?", questionHindi: "यदि किसी वस्तु की कीमत में 25% वृद्धि होती है, तो नई कीमत क्या होगी?", options: ["Original price + 25", "Original price x 1.25", "Original price / 1.25", "Original price - 25"], correct: 1, subject: "Math"},
  {id: 133, question: "Find the next number in the series: 2, 4, 8, 16, ?", questionHindi: "सिरिज़ में अगला संख्या ज्ञात करें: 2, 4, 8, 16, ?", options: ["18", "24", "32", "30"], correct: 2, subject: "Math"},
  {id: 134, question: "If a train travels 60 km in 1 hour, what is its speed?", questionHindi: "यदि एक ट्रेन 1 घंटे में 60 किमी यात्रा करती है, तो इसकी गति क्या है?", options: ["40 km/h", "50 km/h", "60 km/h", "70 km/h"], correct: 2, subject: "Math"},
  {id: 135, question: "The area of a rectangle with length 10 cm and breadth 5 cm is?", questionHindi: "10 सेमी लंबाई और 5 सेमी चौड़ाई वाले आयत का क्षेत्रफल क्या होगा?", options: ["50 cm²", "40 cm²", "60 cm²", "30 cm²"], correct: 0, subject: "Math"},
  {id: 136, question: "Simplify: 15 ÷ 3 + 2 × 5", questionHindi: "सरलीकरण करें: 15 ÷ 3 + 2 × 5", options: ["15", "17", "20", "13"], correct: 1, subject: "Math"},
  {id: 137, question: "If 5 pens cost Rs. 45, what is the cost of 8 pens?", questionHindi: "अगर 5 पेन की कीमत 45 रुपये है, तो 8 पेन की कीमत क्या होगी?", options: ["72 Rs.", "70 Rs.", "80 Rs.", "75 Rs."], correct: 0, subject: "Math"},
  {id: 138, question: "How many vertices does a cube have?", questionHindi: "एक घन के कितने शीर्ष होते हैं?", options: ["6", "8", "12", "10"], correct: 1, subject: "Math"},
  {id: 139, question: "What is the value of 3² + 4²?", questionHindi: "3² + 4² का मान क्या है?", options: ["25", "12", "16", "20"], correct: 0, subject: "Math"},
  {id: 140, question: "If the circumference of a circle is 31.4 cm, what is its radius? (π=3.14)", questionHindi: "यदि एक वृत्त का परिधि 31.4 सेमी है, तो इसका त्रिज्या क्या होगा? (π=3.14)", options: ["5 cm", "10 cm", "15 cm", "20 cm"], correct: 0, subject: "Math"},
  {id: 141, question: "Logical Reasoning: What comes next in the series? 1, 4, 9, 16, ?", questionHindi: "तर्कशक्ति: श्रृंखला में अगला क्या आएगा? 1, 4, 9, 16, ?", options: ["20", "25", "30", "36"], correct: 1, subject: "Reasoning"},
  {id: 142, question: "If A is taller than B, and B is taller than C, who is shortest?", questionHindi: "यदि A, B से लंबा है, और B, C से लंबा है, तो सबसे छोटा कौन है?", options: ["A", "B", "C", "Cannot determine"], correct: 2, subject: "Reasoning"},
  {id: 143, question: "Find the odd one out: Apple, Banana, Mango, Carrot", questionHindi: "असामान्य चीज़ खोजें: सेब, केला, आम, गाजर", options: ["Apple / सेब", "Banana / केला", "Mango / आम", "Carrot / गाजर"], correct: 3, subject: "Reasoning"},
  {id: 144, question: "Which figure completes the series?", questionHindi: "कौन सी आकृति श्रृंखला पूरी करती है?", options: ["Circle", "Square", "Triangle", "Rectangle"], correct: 0, subject: "Reasoning"},
  {id: 145, question: "If all cats are animals, and all animals are living beings, are all cats living beings?", questionHindi: "यदि सभी बिल्लियाँ जानवर हैं, और सभी जानवर जीवित प्राणी हैं, तो क्या सभी बिल्लियाँ जीवित प्राणी हैं?", options: ["Yes / हाँ", "No / नहीं"], correct: 0, subject: "Reasoning"},
  {id: 146, question: "If 5 workers can build a wall in 10 days, how many days will 10 workers take?", questionHindi: "5 मजदूर एक दीवार 10 दिनों में बना सकते हैं, 10 मजदूर कितने दिनों में बनाएंगे?", options: ["5 days / 5 दिन", "10 days / 10 दिन", "15 days / 15 दिन", "20 days / 20 दिन"], correct: 0, subject: "Reasoning"},
  {id: 147, question: "Find the missing number: 2, 6, 12, __, 30", questionHindi: "खोया हुआ संख्या खोजें: 2, 6, 12, __, 30", options: ["16", "18", "20", "22"], correct: 1, subject: "Reasoning"},
  {id: 148, question: "What is the capital of Bihar?", questionHindi: "बिहार की राजधानी क्या है?", options: ["Patna / पटना", "Gaya / गया", "Bhagalpur / भागलपुर", "Muzaffarpur / मुजफ्फरपुर"], correct: 0, subject: "GK"},
  {id: 149, question: "What is India's national animal?", questionHindi: "भारत का राष्ट्रीय पशु क्या है?", options: ["Lion / सिंह", "Elephant / हाथी", "Tiger / बाघ", "Peacock / मोर"], correct: 2, subject: "GK"},
  {id: 150, question: "Which of the following is India's longest highway?", questionHindi: "निम्नलिखित में से भारत की सबसे लंबी राजमार्ग कौन सी है?", options: ["NH44", "NH48", "NH7", "NH52"], correct: 0, subject: "GK"},
];

// Combine all sections into the main question bank
const paper1NewSetQuestions = [
    ...paper1NewSetHistory,
    ...paper1NewSetGeography,
    ...paper1NewSetRemaining,
    ...paper1NewSetPedagogyOthers,
    ...paper1NewSetOtherSubjects
];

// Export for use in exam page
window.paper1NewSetQuestions = paper1NewSetQuestions;

